package ru.pelengator.driver;

/**
 * Набор статусов от драйвера
 */
public enum FT_STATUS {
    FT_OK("FT_OK"),
    FT_INVALID_HANDLE("FT_INVALID_HANDLE"),
    FT_DEVICE_NOT_FOUND("FT_DEVICE_NOT_FOUND"),
    FT_DEVICE_NOT_OPENED("FT_DEVICE_NOT_OPENED"),
    FT_IO_ERROR("FT_IO_ERROR"),
    FT_INSUFFICIENT_RESOURCES("FT_INSUFFICIENT_RESOURCES"),
    FT_INVALID_PARAMETER("FT_INVALID_PARAMETER"),
    FT_INVALID_BAUD_RATE("FT_INVALID_BAUD_RATE"),
    FT_DEVICE_NOT_OPENED_FOR_ERASE("FT_DEVICE_NOT_OPENED_FOR_ERASE"),
    FT_DEVICE_NOT_OPENED_FOR_WRITE("FT_DEVICE_NOT_OPENED_FOR_WRITE"),
    FT_FAILED_TO_WRITE_DEVICE("FT_FAILED_TO_WRITE_DEVICE"),
    FT_EEPROM_READ_FAILED("FT_EEPROM_READ_FAILED"),
    FT_EEPROM_WRITE_FAILED("FT_EEPROM_WRITE_FAILED"),
    FT_EEPROM_ERASE_FAILED("FT_EEPROM_ERASE_FAILED"),
    FT_EEPROM_NOT_PRESENT("FT_EEPROM_NOT_PRESENT"),
    FT_EEPROM_NOT_PROGRAMMED("FT_EEPROM_NOT_PROGRAMMED"),
    FT_INVALID_ARGS("FT_INVALID_ARGS"),
    FT_NOT_SUPPORTED("FT_NOT_SUPPORTED"),
    FT_NO_MORE_ITEMS("FT_NO_MORE_ITEMS"),
    FT_TIMEOUT("FT_TIMEOUT"),
    FT_OPERATION_ABORTED("FT_OPERATION_ABORTED"),
    FT_RESERVED_PIPE("FT_RESERVED_PIPE"),
    FT_INVALID_CONTROL_REQUEST_DIRECTION("FT_INVALID_CONTROL_REQUEST_DIRECTION"),
    FT_INVALID_CONTROL_REQUEST_TYPE("FT_INVALID_CONTROL_REQUEST_TYPE"),
    FT_IO_PENDING("FT_IO_PENDING"),
    FT_IO_INCOMPLETE("FT_IO_INCOMPLETE"),
    FT_HANDLE_EOF("FT_HANDLE_EOF"),
    FT_BUSY("FT_BUSY"),
    FT_NO_SYSTEM_RESOURCES("FT_NO_SYSTEM_RESOURCES"),
    FT_DEVICE_LIST_NOT_READY("FT_DEVICE_LIST_NOT_READY"),
    FT_DEVICE_NOT_CONNECTED("FT_DEVICE_NOT_CONNECTED"),
    FT_INCORRECT_DEVICE_PATH("FT_INCORRECT_DEVICE_PATH"),
    FT_OTHER_ERROR("FT_OTHER_ERROR"),

    FT_MY_ERROR("MY_ERROR"),
    FT_TESTING("MY_TESTING");

    FT_STATUS(String value) {
        this.value = value;
    }

    public final String value;

    public String getValue() {
        return this.value;
    }
}
